<div class="center-block">

    <div class="row"><br></div>

    <div class="row">
        <h3> Venda de Produtos </h3>
    </div>

    <div class="row"><br></div>

    <div class="row">
        <h4>Venda Atual: 1</h4>
    </div>

    <div class="row"><br></div>

    <div class="row">

        <!-- Listagem de produtos da venda -->
        <div class="col-md-6">
            <h4>Lista de Produtos da Venda:<h4>
            
            <!-- Table -->
            <table class="table table-striped table-hover table-responsive">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Descrição</th>
                        <th>Preço</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td width="20%">1</td>
                        <td width="40%">Otto</td>
                        <td width="40%">@mdo</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Thornton</td>
                        <td>@fat</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>the Bird</td>
                        <td>@twitter</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- Incluir produtos na venda -->
        <div class="col-md-6">

            <div class="col-md-12">
                <h4>Produto:</h4>
            </div>

            <div class="col-md-12">
                <input type="text" class="form-control" name="filtroproduto" id="filtroproduto" placeholder="Código ou Descrição">
            </div>

            <div class="col-md-12 text-right" style="margin-top: 5px;">
                <button type="button" class="btn btn-primary">
                    Ok
                </button>
            </div>
        </div>

    </div>

    <div class="row"><br></div>

    <div class="row">
        <div class="col-md-6 text-left">
            <a class="btn btn-default" role="button" href="<?= $this->url('home'); ?>">
                Cancelar
            </a>
        </div>

        <div class="col-md-6 text-right">
            <button type="button" class="btn btn-primary">
                Confirmar
            </button>
        </div>
    </div>
</div>