<?= $this->inlineScript()
            ->prependFile($this->basePath('angular/documento.js'))
        ?>


<div class="center-block" ng-app="AppDocumento" ng-controller="DocumentoController">

    <div class="row"><br></div>

    <div class="row">
        <h3> Venda de Produtos </h3>
    </div>

    <div class="row"><br></div>

    <div class="row">
        <h4>Venda Atual: {{arrDadosVenda.id_documento}}</h4>
    </div>

    <div class="row"><br></div>

    <div class="row">

        <!-- Listagem de produtos da venda -->
        <div class="col-md-6">
            <h4>Lista de Produtos da Venda:<h4>
            
            <div class="row" ng-show="arrProdutosVenda.length > 0">
                <!-- Table -->
                <table class="table table-striped table-hover table-responsive">
                <thead>
                <tr>
                    <th>Código</th>
                    <th>Descrição</th>
                    <th>Preço</th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat=" (key, produto) in arrProdutosVenda">
                    <td width="20%">{{produto.ds_codigo_produto}}</td>
                    <td width="40%">{{produto.ds_produto}}</td>
                    <td width="40%">{{produto.vl_produto}}</td>
                </tr>
                </tbody>
            </table>
            </div>

            <div class="row" ng-show="arrProdutosVenda.length == 0">
                <div class="alert alert-warning">
                    Favor adicionar um produto a venda!
                </div>
            </div>
        </div>

        <!-- Incluir produtos na venda -->
        <div class="col-md-6">

            <div class="col-md-12">
                <h4>Produto:</h4>
            </div>

            <div class="col-md-12">
                <input type="text" class="form-control" name="filtroproduto" id="filtroproduto"  ng-model="filtroproduto" placeholder="Código do produto">
            </div>

            <div class="col-md-12 text-right" style="margin-top: 5px;">
                <button type="button" class="btn btn-primary" ng-click="realizarFiltro()" ng-disabled="snAtualizandoVenda">
                    Ok <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
            </div>

            <div class="col-md-12"  style="margin-top: 5px;">
                <div class="alert alert-success" ng-show="snProdutoFiltradoExiste === false">
                    <a href="#" class="alert-link">Produto não cadastrado!</a>
                </div>        
            </div>

    </div>

    <div class="row"><br></div>

    <div class="row">
        <div class="col-md-6 text-left">
            <a class="btn btn-default" role="button" ng-click="cancelarVenda()">
                Cancelar
            </a>
        </div>

        <div class="col-md-6 text-right">
            <button type="button" class="btn btn-primary" ng-click="confirmarVenda()">
                Confirmar
            </button>
        </div>
    </div>
</div>