<?= $this->inlineScript()
            ->prependFile($this->basePath('angular/produto.min.js'))
        ?>

<div class="center-block" ng-app="AppProduto" ng-controller="ProdutoController">

    <div class="row">
        <h3> Cadastro de Produtos </h3>
    </div>

    <div class="row"><br></div>

    <div class="row">
        <div class="panel panel-info">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <h4>Filtrar Produtos</h4>
            </div>
            <div class="panel-body">
                <input type="text" class="form-control" ng-model="filtroproduto" name="filtroproduto" id="filtroproduto" placeholder="Código ou Descrição">
                <button type="button" class="btn btn-info" style="margin-top:5px;" ng-click="realizarFiltro()">
                    Filtrar <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
            </div>
        </div>
    </div>

    <div class="row">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
            Incluir <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        </button>
    </div>
    
    <div class="row"><br></div>

    <div class="row" ng-show="arrProdutos.length > 0">
        <!-- Table -->
        <table class="table table-striped table-hover table-responsive">
        <thead>
          <tr>
            <th>Código</th>
            <th>Descrição</th>
            <th>Preço</th>
          </tr>
        </thead>
        <tbody>
          <tr ng-repeat=" (key, produto) in arrProdutos">
            <td width="20%">{{produto.ds_codigo_produto}}</td>
            <td width="40%">{{produto.ds_produto}}</td>
            <td width="40%">{{produto.vl_produto}}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="row" ng-show="arrProdutos.length == 0">
        <div class="alert alert-warning">
            Favor realizar um filtro valido para visualizar os produtos!
        </div>
    </div>

    <div class="row"><br></div>

    <div class="row">
        <a class="btn btn-default" role="button" href="<?= $this->url('home'); ?>">
            Voltar
        </a>
    </div>

    <!-- Modal de inclusão de produto -->
    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Incluir Produto</h4>
            </div>
            <div class="modal-body row">
                <div class="container  col-md-2 text-right">
                    Código:
                </div>
                
                <div class="container  col-md-10">
                    <input type="text" class="form-control" ng-model="arrNovoProduto.ds_codigo_produto" name="codigo" id="codigo" >
                </div>
                <div class="container  col-md-12"><br></div>
                <div class="container  col-md-2 text-right">
                    Descrição:
                </div>
                <div class="container  col-md-10">
                    <input type="text" class="form-control" ng-model="arrNovoProduto.ds_produto" name="descricao" id="descricao">
                </div>
                <div class="container  col-md-12"><br></div>
                <div class="container  col-md-2 text-right">
                    Preço:
                </div>
                <div class="container  col-md-6">
                    <input type="text" class="form-control" ng-model="arrNovoProduto.vl_produto" name="preco" id="preco" onkeypress="return isNumberKey(event)">
                </div>

                <div class="container  col-md-12">
                    <div class="alert alert-success" ng-show="snProdutoInserido">
                        <a href="#" class="alert-link">Produto Inserido com sucesso!</a>
                    </div>

                    <div class="alert alert-warning" ng-show="snFiltroValido === false">
                        <a href="#" class="alert-link">Favor informar o código do produto!</a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="botaoCancelar" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" ng-click="adicionarProduto()" ng-disabled="snAtualizandoProduto">Incluir</button>
            </div>
            </div>
        </div>
    </div>
    
</div>