<div class="center-block">

    <div class="row"><br></div>

    <div class="row">
        <h3> Cadastro de Produtos </h3>
    </div>

    <div class="row"><br></div>

    <div class="row">
        <div class="panel panel-info">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <h4>Filtrar Produtos</h4>
            </div>
            <div class="panel-body">
                <input type="text" class="form-control" name="filtroproduto" id="filtroproduto" placeholder="Código ou Descrição">
                <button type="button" class="btn btn-info" style="margin-top:5px;">
                    Filtrar <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
            </div>
        </div>
    </div>

    <div class="row">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
            Incluir <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        </button>
    </div>
    
    <div class="row"><br></div>

    <div class="row">
        <!-- Table -->
        <table class="table table-striped table-hover table-responsive">
        <thead>
          <tr>
            <th>Código</th>
            <th>Descrição</th>
            <th>Preço</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td width="20%">1</td>
            <td width="40%">Otto</td>
            <td width="40%">@mdo</td>
          </tr>
          <tr>
            <td>2</td>
            <td>Thornton</td>
            <td>@fat</td>
          </tr>
          <tr>
            <td>3</td>
            <td>the Bird</td>
            <td>@twitter</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="row"><br></div>

    <div class="row">
        <a class="btn btn-default" role="button" href="<?= $this->url('home'); ?>">
            Voltar
        </a>
    </div>

    <!-- Modal de inclusão de produto -->
    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Incluir Produto</h4>
            </div>
            <div class="modal-body row">
                <div class="container  col-md-2 text-right">
                    Código:
                </div>
                
                <div class="container  col-md-10">
                    <input type="text" class="form-control" name="codigo" id="codigo" >
                </div>
                <div class="container  col-md-12"><br></div>
                <div class="container  col-md-2 text-right">
                    Descrição:
                </div>
                <div class="container  col-md-10">
                    <input type="text" class="form-control" name="descricao" id="descricao">
                </div>
                <div class="container  col-md-12"><br></div>
                <div class="container  col-md-2 text-right">
                    Preço:
                </div>
                <div class="container  col-md-6">
                    <input type="text" class="form-control" name="preco" id="preco">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary">Incluir</button>
            </div>
            </div>
        </div>
    </div>
    
</div>