<?= $this->doctype() ?>

<html lang="en">
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <?= $this->headTitle('Desafio TSIC')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/estilo.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-1.11.3.min.js'))
            ->prependFile($this->basePath('js/angular.min.js'))
        ?>
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-default ">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#">Vendas TSIC</a>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">

                        <ul class="nav navbar-nav navbar-right">
                        <li><a href="./">Inicio</a></li>
                        <li><a href="<?= $this->url('produto'); ?>">Produto</a></li>
                        <li><a href="<?= $this->url('documento'); ?>">Venda</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div><!--/.container-fluid -->
            </nav>

            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
