<div class="center-block">

    <div class="row"><br></div>

    <div class="row text-center">
        <h2> Sistema de Vendas - Desafio TSIC</h2>
    </div>

    <div class="row"><br></div>
    <div class="row"><br></div>

    <div class="row">
        <div class="btn-group btn-group-lg btn-group-justified">
            <a class="btn btn-default" role="button" href="<?= $this->url('produto'); ?>">Cadastro de Produtos</a>
            <a class="btn btn-default" role="button" href="<?= $this->url('documento'); ?>">Venda de Produtos</a>
        </div>
    </div>
</div>