<?= $this->inlineScript()
            ->prependFile($this->basePath('angular/index.min.js'))
        ?>

<div class="center-block" ng-app="AppIndex" ng-controller="IndexController">
    <div class="row text-center">
        <h2> Sistema de Vendas - Desafio TSIC</h2>
    </div>

    <div class="row"><br></div>
    <div class="row"><br></div>

    <div class="row hidden-xs">
        <div class="btn-group btn-group-lg btn-group-justified">
            <a class="btn btn-default" role="button" href="<?= $this->url('produto'); ?>">Cadastro de Produtos</a>
            <a class="btn btn-default" role="button" href="<?= $this->url('documento'); ?>">Venda de Produtos</a>
        </div>
    </div>

    <div class="row visible-xs">
        <div class="btn-group btn-group-justified">
            <a class="btn btn-default" role="button" href="<?= $this->url('produto'); ?>">Cadastro de Produtos</a>
            <a class="btn btn-default" role="button" href="<?= $this->url('documento'); ?>">Venda de Produtos</a>
        </div>
    </div>

    <div class="row"><br></div>

    <div class="col-sm-12" ng-show="snValorTotalRecuperado">
        <h3> Area do Administrador </h3>
    </div>


    <div class="col-sm-6" ng-show="snValorTotalRecuperado">
        <div class="card card-default">
        <div class="card-body">
            <p class="lead">Valor total das vendas:</p>
            <p class="lead">R$ {{valorTotalVenda}}</p>
        </div>
        </div>
    </div>
</div>